"""Risk scorer: rates severity and impact from 1 to 5 with a one-sentence reason.

Only scores events the verifier accepted (verdict "yes"). The model sees the verifier's
reason and verbatim quote, not the whole article, so scores rest on checked evidence.
The event ID, site ID and source URL are copied in Python, never generated by the model.

Input:  ScoringRequest
Output: RiskScore
"""

from collections.abc import Awaitable, Callable

from google.adk.agents import LlmAgent

from scrm.agents._adk import run_structured
from scrm.config import Settings, get_settings
from scrm.schemas import RiskJudgement, RiskScore, ScorerInput, ScoringRequest, Verdict
from scrm.telemetry import RunContext, get_logger

NAME = "risk_scorer"
INPUT_SCHEMA = ScoringRequest
OUTPUT_SCHEMA = RiskScore
DESCRIPTION = (__doc__ or "").splitlines()[0]

log = get_logger(__name__)

INSTRUCTION = """\
You score supply chain risk for a laptop maker. The input is JSON with one monitored site
(a port, factory or shipping chokepoint) and a verified disruption: the verifier's
one-sentence reason, a verbatim quote from the source article, and how many articles
covered the story (cluster_size).

Score two things from 1 to 5, using only the evidence given:

severity: how serious the event is in itself.
  1 minor, routine or already resolved (a short local delay)
  2 limited, hours to a day, little wider effect
  3 significant, days of disruption or a clear safety or security incident
  4 major, a week or more, or widespread across a region
  5 extreme, prolonged closure, disaster or conflict

impact: how much it disrupts THIS site's operations or cargo flows.
  1 indirect, affects the surroundings but not the site's throughput
  2 small, some delays or extra cost at the site
  3 moderate, reduced capacity or rerouting at the site
  4 large, the site is badly constrained
  5 the site is shut or cargo through it is halted

reason: exactly one sentence in English explaining both scores.
Do not raise scores for wide coverage alone; cluster_size only shows how visible it is.
"""


def build_agent(settings: Settings) -> LlmAgent:
    """Return the ADK agent definition. Constructing it makes no network calls."""
    return LlmAgent(
        name=NAME,
        model=settings.gemini_model,
        description=DESCRIPTION,
        instruction=INSTRUCTION,
        input_schema=ScorerInput,
        output_schema=RiskJudgement,
        output_key=NAME,
    )


Scorer = Callable[[ScorerInput], Awaitable[RiskJudgement]]


async def _gemini_score(payload: ScorerInput) -> RiskJudgement:
    return await run_structured(build_agent(get_settings()), payload, RiskJudgement)


async def run(
    request: ScoringRequest, ctx: RunContext, *, score: Scorer = _gemini_score
) -> RiskScore:
    """Score one verified event within run ``ctx.run_id``."""
    verified = request.verified_event
    if verified.verdict is not Verdict.YES or not verified.quote:
        raise ValueError("only events with a 'yes' verdict can be scored")
    with ctx.bind():
        payload = ScorerInput(
            site=request.site,
            event_date=verified.event.event_date,
            reason=verified.reason,
            quote=verified.quote,
            cluster_size=verified.event.cluster_size,
        )
        judgement = await score(payload)
        result = RiskScore(
            event_id=verified.event.event_id,
            site_id=request.site.site_id,
            severity=judgement.severity,
            impact=judgement.impact,
            reason=judgement.reason,
            source_url=verified.evidence_url,
        )
        log.info(
            "risk_scorer.done",
            extra={
                "event_id": result.event_id,
                "severity": result.severity,
                "impact": result.impact,
                "reason": result.reason,
            },
        )
        return result
